app = "mattbnz-review"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  REPO_URL = "https://github.com/mattbnz/web-matt.git"
  METRICS_REPO_URL = "https://github.com/mattbnz/metrics"

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  tcp_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.http_checks]]
    grace_period = "1s"
    interval = "15s"
    method = "get"
    path = "/healthz"
    protocol = "http"
    restart_limit = 0
    timeout = "2s"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[mounts]
	source="logs"
	destination="/logs"
